### ISSUE TITLE
Does not parse everything?

### ISSUE THREAD

**Issue by BasToTheMax** [Schoonology/node-resp#1]
Hello!

Thanks for making this.
It looks like, it does not parse everything:

# Raw data:
```
d *3
$6
CONFIG
$3
GET
$4
save
*3
$6
CONFIG
$3
GET
$10
appendonly
```

# Parsed data:
```json
[ 'CONFIG', 'GET', 'save' ]
```

As you can see the `CONFIG GET appendonly` part is not getting parsed.

- Why does this happen?
- How can I fix it

**Comment by Schoonology** [comment]
This library doesn't (yet!) support _pipelining_, which is the aspect of the RESP-based request/response protocol it sounds like you're looking for. The ideal answer to the "How can I fix it" half, then, is for someone to add pipelining support to the library.

To better answer the "Why does this happen?" half, take the data you provided line by line. Starting at the top, you specified a three-element array. From this point onward, `resp.parse` (again, lacking pipelining) is expected to respond with a single, three-element array. Which it does: starting with the six-character string `"CONFIG"`, continuing to the three-character string `"GET"`, and ending with the four-character string `"save"`.

At this point the library assumes it's finished, and returns the Array as promised. The extra bits are considered incidental.

**Comment by BasToTheMax** [comment]
Thanks for your response. I will try to implement it.
